const tools=[['💰','Profit Calculator','Know your profit on every sale.','profit'],['📊','Daily Sales','Track sales, costs and profit.','sales'],['📱','M-Pesa Fees','Quick transaction fee estimate.','fees'],['📦','Stock & Pricing','Set a selling price from your cost.','stock'],['🧾','Receipt Generator','Create a simple customer receipt.','receipt'],['💵','Loan Calculator','Estimate monthly repayments.','loan']];
const grid=document.getElementById('toolGrid');grid.innerHTML=tools.map(t=>`<button class="tool" onclick="show('${t[3]}')"><div class="icon">${t[0]}</div><h3>${t[1]}</h3><p>${t[2]}</p></button>`).join('');
function show(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo(0,0)}document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>show(b.dataset.nav));document.querySelectorAll('.back').forEach(b=>b.onclick=()=>show('home'));
const ksh=n=>`KSh ${Number(n||0).toLocaleString('en-KE',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
function calcProfit(){let b=+buyPrice.value,s=+sellPrice.value,q=+qty.value||1,c=(s-b)*q;profitResult.innerHTML=`<div class="stat">Profit<strong>${ksh(c)}</strong></div><div class="stat">Total sales<strong>${ksh(s*q)}</strong></div><div class="stat">Profit per item<strong>${ksh(s-b)}</strong></div>`}
let sales=JSON.parse(localStorage.getItem('mbt-sales')||'[]');function renderSales(){salesDate.textContent=new Date().toLocaleDateString('en-KE',{weekday:'long',day:'numeric',month:'short',year:'numeric'});salesList.innerHTML=sales.length?sales.map((x,i)=>`<div class="sale"><div><b>${x.name}</b><small>Cost ${ksh(x.cost)}</small></div><div><b>${ksh(x.amount)}</b><small>Profit ${ksh(x.amount-x.cost)}</small></div></div>`).join(''):'<p class="muted">No sales added yet.</p>';let total=sales.reduce((a,x)=>a+x.amount,0),cost=sales.reduce((a,x)=>a+x.cost,0);salesSummary.innerHTML=`<div class="stat">Today’s sales<strong>${ksh(total)}</strong></div><div class="stat">Today’s profit<strong>${ksh(total-cost)}</strong></div>`}function addSale(){let n=saleName.value.trim(),a=+saleAmount.value,c=+saleCost.value;if(!n||a<0)return;sales.push({name:n,amount:a,cost:c});localStorage.setItem('mbt-sales',JSON.stringify(sales));saleName.value='';saleAmount.value='';saleCost.value='';renderSales()}function clearSales(){if(confirm('Clear today’s sales?')){sales=[];localStorage.setItem('mbt-sales','[]');renderSales()}}renderSales();
function calcStock(){let c=+stockCost.value||0,m=+margin.value||0,q=+stockQty.value||1,price=c/(1-m/100);stockResult.innerHTML=`<div class="stat">Recommended selling price<strong>${ksh(price)}</strong></div><div class="stat">Profit per item<strong>${ksh(price-c)}</strong></div><div class="stat">Total profit (${q} items)<strong>${ksh((price-c)*q)}</strong></div>`}
function calcFee(){let a=+feeAmount.value||0,type=feeType.value;let fee=0;if(type==='deposit')fee=0;else if(type==='send'){if(a<=100)fee=6;else if(a<=500)fee=7;else if(a<=1000)fee=13;else if(a<=1500)fee=23;else if(a<=2500)fee=33;else if(a<=3500)fee=53;else if(a<=5000)fee=57;else if(a<=7500)fee=78;else if(a<=10000)fee=90;else fee=108;}else{fee=a<=50?0:a<=2500?32:a<=5000?69:a<=10000?115:a<=15000?167:a<=20000?185:197}feeResult.innerHTML=`<div class="stat">Estimated fee<strong>${ksh(fee)}</strong></div><p class="muted">Tariffs can change. Verify the current Safaricom tariff before relying on this figure.</p>`}
function makeReceipt(){let biz=bizName.value||'My Business',cust=customer.value||'Customer',item=receiptItem.value||'Item',q=+receiptQty.value||1,p=+receiptPrice.value||0,total=q*p;receiptOutput.innerHTML=`<div class="receipt" id="printReceipt"><h3>${biz}</h3><p>Customer: ${cust}</p><div class="line"><span>${item} × ${q}</span><b>${ksh(total)}</b></div><div class="line"><b>Total</b><b>${ksh(total)}</b></div><p class="muted" style="text-align:center">Thank you for your business 🇰🇪</p><button class="primary" onclick="shareReceipt('${encodeURIComponent(biz)}','${encodeURIComponent(item)}','${total}')">Share on WhatsApp</button></div>`}function shareReceipt(b,i,t){let msg=`${decodeURIComponent(b)}%0AReceipt%0A${decodeURIComponent(i)}%0ATotal: KSh ${Number(t).toLocaleString()}%0AThank you for your business!`;window.open(`https://wa.me/?text=${msg}`,'_blank')}
function calcLoan(){let P=+loanAmount.value||0,r=(+loanRate.value||0)/100/12,n=+loanMonths.value||1,m=r?P*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):P/n;loanResult.innerHTML=`<div class="stat">Estimated monthly payment<strong>${ksh(m)}</strong></div><div class="stat">Total repayment<strong>${ksh(m*n)}</strong></div><div class="stat">Estimated interest<strong>${ksh(m*n-P)}</strong></div><p class="muted">This assumes a standard reducing-balance monthly repayment and excludes fees or insurance.</p>`}
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;installBtn.classList.remove('hidden')});installBtn.onclick=async()=>{if(deferred){deferred.prompt();deferred=null;installBtn.classList.add('hidden')}};
